[package]
name = "submit_quiz"
version = "0.1.0"
edition = "2021"

[lib]
name = "submit_quiz"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.23", features = ["extension-module"] }

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
strip = true
panic = "abort"
